<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
   <S:Body>
      <ns2:getPriceForAllStockResponse xmlns:ns2="http://contacts.ws.aashita.com/">
         <return>
            <close_price>0.0</close_price>
            <deliv_qty>0</deliv_qty>
            <high_price>0.0</high_price>
            <id>265</id>
            <last_price>949.7047</last_price>
            <low_price>0.0</low_price>
            <open_price>0.0</open_price>
            <prev_close>0.0</prev_close>
            <symbol>EXIDEIND</symbol>
         </return>
         <return>
            <close_price>0.0</close_price>
            <deliv_qty>0</deliv_qty>
            <high_price>0.0</high_price>
            <id>758</id>
            <last_price>530.3663</last_price>
            <low_price>0.0</low_price>
            <open_price>0.0</open_price>
            <prev_close>0.0</prev_close>
            <symbol>HIKAL</symbol>
         </return>
         <return>
            <close_price>0.0</close_price>
            <deliv_qty>0</deliv_qty>
            <high_price>0.0</high_price>
            <id>812</id>
            <last_price>839.74475</last_price>
            <low_price>0.0</low_price>
            <open_price>0.0</open_price>
            <prev_close>0.0</prev_close>
            <symbol>CONCUR</symbol>
         </return>
         <return>
            <close_price>0.0</close_price>
            <deliv_qty>0</deliv_qty>
            <high_price>0.0</high_price>
            <id>322</id>
            <last_price>354.68793</last_price>
            <low_price>0.0</low_price>
            <open_price>0.0</open_price>
            <prev_close>0.0</prev_close>
            <symbol>DABUR</symbol>
         </return>
         <return>
            <close_price>0.0</close_price>
            <deliv_qty>0</deliv_qty>
            <high_price>0.0</high_price>
            <id>876</id>
            <last_price>159.67279</last_price>
            <low_price>0.0</low_price>
            <open_price>0.0</open_price>
            <prev_close>0.0</prev_close>
            <symbol>ITC</symbol>
         </return>
         <return>
            <close_price>0.0</close_price>
            <deliv_qty>0</deliv_qty>
            <high_price>0.0</high_price>
            <id>666</id>
            <last_price>49.835503</last_price>
            <low_price>0.0</low_price>
            <open_price>0.0</open_price>
            <prev_close>0.0</prev_close>
            <symbol>NIFTYBEES</symbol>
         </return>
      </ns2:getPriceForAllStockResponse>
   </S:Body>
</S:Envelope>