#%RAML 1.0 DataType
type: 
  properties:
    id:
      required: true
      type: integer
    name:
      required: true
      type: string
    lname:
      required: false
      type: string
    city:
      required: false
      type: string
      